previewsEnabled: true
services:
  - name: create-react-app
    type: web
    runtime: static
    buildCommand: yarn install && yarn buildCommand
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: index.html 