previewsEnabled: off
services:
  - name: create-react-app
    repo: https://github.com/kwlockwo/render-create-react-app
    type: web
    runtime: static
    previews:
      generation: automatic
    buildCommand: yarn install && yarn build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: index.html
